[env]
TERM="xterm-256color"

[colors.primary]
background = "#1f1f39"
foreground = "#ffffff"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.normal]
red = "#ff6e6e"
green = "#6be28d"
yellow = "#fbdda7"
blue = "#b3e3f2"
white = "#ffffff"
black = "#9aa4ca"
# magenta = "#ca5c26"
# cyan = "#ca5c26"

[colors.bright]
red = "#ff6e6e"
green = "#6be28d"
yellow = "#fbdda7"
blue = "#b3e3f2"
white = "#ffffff"
black = "#9aa4ca"
# magenta = "#ca5c26"
# cyan = "#ca5c26"


[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
